import mongoose from 'mongoose';
import {
  CALL_END_REASONS,
  CALL_PARTICIPANT_ROLE,
  CALL_STATUS,
  CALL_STATUSES,
  CALL_TYPE,
  CALL_TYPES,
  PENDING_CALL_STATUSES,
} from './call.constants.js';

const { Schema, model, models } = mongoose;

/**
 * Backend-determined participant entry. `identity` is the LiveKit identity
 * generated by the server (`user:<userId>`), `role` says how that participant
 * relates to the call. Clients never supply either value.
 */
const participantSchema = new Schema(
  {
    userId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    identity: { type: String, required: true, trim: true, maxlength: 120 },
    role: { type: String, enum: Object.values(CALL_PARTICIPANT_ROLE), required: true },

    // Presence inside the LiveKit room, maintained by verified webhooks only.
    joinedAt: { type: Date, default: null },
  },
  { _id: false }
);

/**
 * Application-side emergency call record.
 *
 * `roomName` is generated/stored by the backend — clients can only reference a
 * call by `callId` and can never choose the LiveKit room they join.
 * `identities` optionally stores per-user participant identities so repeated
 * token requests reuse the same identity within the room.
 * `participants` records both participants with their backend-generated
 * identity and role.
 */
const callSchema = new Schema(
  {
    sosId: { type: Schema.Types.ObjectId, ref: 'SosEvent', required: true },

    // Protected user who owns the SOS and receives the call.
    userId: { type: Schema.Types.ObjectId, ref: 'User', required: true },

    // Invited guardian participating in the call (while ringing/connected).
    guardianUserId: { type: Schema.Types.ObjectId, ref: 'User', default: null },

    // Single supported call type — stored, never branched on.
    type: { type: String, enum: CALL_TYPES, default: CALL_TYPE.BROWSER_TO_BROWSER },

    roomName: { type: String, required: true, trim: true, maxlength: 120 },

    status: { type: String, enum: CALL_STATUSES, default: CALL_STATUS.CREATED },

    participants: { type: [participantSchema], default: () => [] },

    // { [userId]: participantIdentity } — optional backend-managed reuse.
    identities: { type: Schema.Types.Mixed, default: () => ({}) },

    startedAt: { type: Date, default: null },
    ringingAt: { type: Date, default: null },
    connectedAt: { type: Date, default: null },
    endedAt: { type: Date, default: null },

    // Why the call ended — one of CALL_END_REASONS, set by `/calls/end`.
    endReason: { type: String, enum: [...CALL_END_REASONS, null], default: null },
  },
  {
    timestamps: true,
    collection: 'calls',
  }
);

callSchema.index({ userId: 1, status: 1 });
callSchema.index({ sosId: 1 });

/**
 * At most ONE in-flight call per SOS — enforced by the database, not by the
 * frontend, so two concurrent `/calls/start` requests cannot both win.
 *
 * The partial filter keeps terminal calls (ENDED / FAILED / CANCELLED /
 * REJECTED) out of the index, so a finished call never blocks a retry.
 *
 * The explicit `name` matters: MongoDB allows the same key pattern under a
 * different name, and a legacy non-unique `sosId_1` index may already exist on
 * deployed databases (creating `sosId_1` again with new options would fail).
 */
callSchema.index(
  { sosId: 1 },
  {
    name: 'sosId_active_unique',
    unique: true,
    partialFilterExpression: { status: { $in: [...PENDING_CALL_STATUSES] } },
  }
);

export const Call = models.Call || model('Call', callSchema);
